#%RAML 1.0 NamedExample
accounts-examples:
-
  accountID: 100
  name: James
  street: downtown
  city: Nellore
  state: andhr pradesh
  postal: 524001
  country: india

-
  accountID: 101
  name: John
  street: Khuddus nagar
  city: Guntur
  state: andhra pradesh
  postal: 52314
  country: india



